### ISSUE TITLE
API reports 1.7.8 as published

### ISSUE THREAD

**Issue by LeoColomb** [YOURLS/api.yourls.org-public#2]
https://discourse.yourls.org/t/1-7-8-version-banner-but-not-linked-to-github/206/4

**Comment by ozh** [comment]
Fixed. Moving all code from bitbucket to github (private repo) as soon as I have cleaned the code.

**Comment by LeoColomb** [comment]
@ozh Don't hesistate to add it to the YOURLS org, GitHub now support private repositories! 👍 
Do you have a backup?

**Comment by ozh** [comment]
I have the complete repo of course. Yes, migrating on https://github.com/YOURLS/api.yourls.org tomorrow
